config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get '/plotter' => 'static_pages#plotter'

  get '/about' => 'static_pages#about'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def plotter
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Plotathing</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body class = "<%= controller_name %> <%= action_name %>">
<div class="container">
	<nav class="navbar navbar-default navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<a id="logo">
					plot-a-thing
				</a>
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				
			</div>
			<div id="navbar" class="navbar-collapse collapse navbar-right" aria-expanded="false" style="height: 0.8px;">
				<ul class="nav navbar-nav">
					<li><%= link_to "Home", root_path %></li>
					<li><%= link_to "Plotter", plotter_path %></li>
					<li><%= link_to "About", about_path %></li>
				</ul>
			</div><!--/.nav-collapse -->
		</div><!--/.container-fluid -->
	</nav>
</div>
	  
<div class="container">
	<div class="row">
	<span class="icon-bar"></span>
		<%= yield %>
	</div>
	
	<hr>
</div>
<footer class="footer">
	<div class="container">
		<p class="text-right">2ID60 | &copy; <%= Time.now.year %> DNEVEL AVIDROKT</p>
	</div>
</footer>

</body>
</html>

app/views/static_pages/about.html.erb
<div class="col-md-12">
		<h1>About</h1>
	</div>
</div> <!-- .row -->

<div class="row">
	<div class="col-md-6">
		<h2>Intro</h2>
		<p>This webapp is created for the subject Web Technology at the TU/e. The purpose of this assignment was to create an interactive webapp. This resulted in a plotter app. On this page you can read more about how to use this basic app.</p>
	</div>
	
	<div class="col-md-6 purple">
		<h2>Usage</h2>
		<ul>
			<li><p>Enter a formula</p></li>
			<li><p>Enter a domain (upper and lower bound)</p></li>
			<li><p>Enter a tick (step size)</p></li>
			<li><p>Enjoy your graph!</p></li>
		</ul>
	</div>
	
</div>

<div class="row">
	<div class="col-md-6 purple">
		<h2>Formulas</h2>
		<p>Plot-A-Thing uses polynomials over x to create a graph. To interpret the input polynomial the plotter uses some plugins. This gives some constraints. For a list of all allowed functions and operations, please have a look into the "Functions" sections. Note that you are only allowed to use x as a variable, any other letter will result in an error.</p>
	</div>
	
	<div class="col-md-6 ">
		<h2>Domain</h2>
		<p>You can set the domain by entering a lower bound (Xmin), an upper bound (Xmax) and a step size (Xtick).</p>
		<p>Even though it might be obvious, Always make sure that Xmax > Xmin, and that Xtick > 0. You can use decimals, use a '.' as separator.</p>
	</div>
	
</div>
<div class="row">
	<div class="col-md-6 ">
		<h2>Functions</h2>
		<p>Plot-A-Thing can handle the following functions and operations:</p>
		<ul class="col-md-6" >
			<li>x*x - Multiplication</li>
			<li>x+x - Addition</li>
			<li>x-x - Subtraction</li>
			<li>x/x - Division</li>
			<li>x^x - Powers</li>
			<li>x%x - Modulus</li>
			<li>log(x) - Logarithm</li>
		</ul>
		<ul class="col-md-6" >
			<li>sin(x) - Sine</li>
			<li>cos(x) - Cosine</li>
			<li>tan(x) - Tangent</li>
			<li>abs(x) - Absolute value</li>
			<li>floor(x) - Round to lower integer</li>
			<li>ceil(x) - Round to upper integer</li>
		</ul>
		<div class="clearfix"></div>
		<p >Note that all but only these functions are tested and can be assumed to work.</p>
	</div>
	
	<div class="col-md-6 purple">
		<h2>Credits</h2>
		<p>Plot-A-Thing is created with help of the following frameworks and plugins:</p>
		<%= link_to image_tag("bootstrap.png", :class => "creditsImg"), "http://www.getbootstrap.com", :target => "_blank" %>
		<%= link_to image_tag("rails.svg",:class => "creditsImg") , "http://rubyonrails.org", :target => "_blank"%>
		<%= link_to image_tag("mathjs.png", :class => "creditsImg"), "http://mathjs.org", :target => "_blank"%>
		<%= link_to image_tag("chartjs.svg",:class => "creditsImg"), "http://chartjs.org", :target => "_blank"%>
		<div class="clearfix"></div>
		<p>Feel free to visit the sites of these plugins by clicking on their logo</p>
		<p
	</div>
	

app/views/static_pages/home.html.erb
	<div class="col-md-12">
		<h1>Home</h1>
	</div>
</div> <!-- .row -->

<div class="row">
	<div class="col-md-6">
		<p>Welcome to Plot-a-Thing. Thank you for visiting this webapp! You can use this webapp to <%= link_to "plot", plotter_path %> any polynomial you want. This will give you nice graphs which will clearly indicate the shape of the graph for you!</p>
		
		<p>Before starting to plot, you can <%= link_to "read", about_path %> some information on how to use this plotter</p>
	</div>
	
	<a href="<%= plotter_path %>"><div class="col-md-6 purple">
		<h1>Start plotting!</h1>
		<p>Click here to start plotting right away.</p>
	</div></a>
	
</div>

<div class="row">
	<div class="col-md-12 gray">
		<canvas id="introChart" width="400" height="200"></canvas>
	</div>

app/views/static_pages/plotter.html.erb
<div class="col-md-12 gray">
	<h1>Plotter</h1>
	<hr>
	<p>Please fill in your formula here (use x as variable):</p>
	<p>f(x) = <input id="usrFormula" type="text"/></p>
	
	<table>
		<thead><tr>
			<th class="col-md-4">Xmin</th>
			<th class="col-md-4">Xmax</th>
			<th class="col-md-4">Tick</th>
		</tr></thead>
		<tr>
			<td ><input class="interval" id="usrXmin" type="number"/></td>
			<td ><input class="interval" id="usrXmax" type="number"/></td>
			<td ><input class="interval" id="usrXtick" type="number"/></td>
		</tr>
	</table>
	
	<canvas id="myChart" width="400" height="250"></canvas>
</div>